# Generated by Django 3.2.5 on 2021-08-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_controller', '0003_chatlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlist',
            name='favorite',
        ),
    ]
