# Generated by Django 3.2.5 on 2021-08-31 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_controller', '0005_chatlist_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlist',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chatted', to='user_controller.customuser'),
        ),
    ]
