# Generated by Django 3.2.5 on 2021-08-31 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_controller', '0006_alter_chatlist_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlist',
            name='other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chatted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chatlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
