# Generated by Django 3.2.5 on 2021-08-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_main', '0008_auto_20210805_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='likes',
            new_name='like',
        ),
    ]
