# Generated by Django 3.2.5 on 2021-08-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_main', '0011_auto_20210806_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reply_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
