# Generated by Django 3.2.5 on 2021-08-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_main', '0012_alter_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reply_to', to='post_main.reply'),
        ),
    ]
