# Generated by Django 3.2.5 on 2021-08-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_main', '0013_alter_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='reply',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='post_main.reply'),
        ),
    ]
