# Generated by Django 3.2.5 on 2021-08-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_main', '0014_auto_20210806_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='reply',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='comment_reply', to='post_main.Reply'),
        ),
    ]
