# Generated by Django 3.2.5 on 2021-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_main', '0017_auto_20210806_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='reply',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='reply',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_reply', to='post_main.Reply'),
        ),
    ]
