# Generated by Django 3.2.5 on 2021-08-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_main', '0018_auto_20210806_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='comment_reply', to='post_main.Reply'),
        ),
    ]
